### ISSUE TITLE
Implementation build 

### ISSUE THREAD

**Issue by bigautam** [SynBioHub/synbiohub3#536]
The link in the member of collections sends you to synbiohub with an error 
"Error: getType: https://synbiohub.org/user/biga/design_build/design_build_collection/1 not found
    at sparql.queryJson.then (/synbiohub/lib/query/local/type.js:12:29)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)"

**Comment by danielfang97** [comment]
Fixed
