### ISSUE TITLE
Random page leads to permanent loading screen

### ISSUE THREAD

**Issue by danielfang97** [SynBioHub/synbiohub3#617]
It should catch this as an error or invalid page.

**Comment by danielfang97** [comment]
[...view]-db0bc6fb5c0f5654792d.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading '0')
    at [...view]-db0bc6fb5c0f5654792d.js:1:310554
    at p ([...view]-db0bc6fb5c0f5654792d.js:1:303268)
    at Generator.<anonymous> ([...view]-db0bc6fb5c0f5654792d.js:1:304599)
    at Generator.next ([...view]-db0bc6fb5c0f5654792d.js:1:303678)
    at n (e6483d7e165f60fa7a99589ebe5ce1781d619e26.01250d4661cedac1677d.js:1:41044)
    at s (e6483d7e165f60fa7a99589ebe5ce1781d619e26.01250d4661cedac1677d.js:1:41247)
    at e6483d7e165f60fa7a99589ebe5ce1781d619e26.01250d4661cedac1677d.js:1:41306
    at new Promise (<anonymous>)
    at e6483d7e165f60fa7a99589ebe5ce1781d619e26.01250d4661cedac1677d.js:1:41187
    at d ([...view]-db0bc6fb5c0f5654792d.js:1:311465)

**Comment by danielfang97** [comment]
Closed with #618
