### ISSUE TITLE
Submit page throws error

### ISSUE THREAD

**Issue by danielfang97** [SynBioHub/synbiohub3#622]
Couldn't get and/or process submissions
http://localhost:7777/shared
Error Information:
Name
TypeError

Message
undefined is not iterable (cannot read property Symbol(Symbol.iterator))

Response Data
Stack
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator)) at _iterableToArray (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/iterableToArray.js:4:44) at _toConsumableArray (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/toConsumableArray.js:12:155) at _callee8$ (webpack-internal:///./redux/actions.js:1501:126) at tryCatch (webpack-internal:///./redux/actions.js:55:1062) at Generator.eval (webpack-internal:///./redux/actions.js:55:3010) at Generator.eval [as throw] (webpack-internal:///./redux/actions.js:55:1699) at asyncGeneratorStep (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:5:24) at _throw (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:27:9)

**Comment by danielfang97** [comment]
Closing this because this is the same error as #623
